#! NOTE: Please select your desired Rest Client environment before running the tests !#

### Home page
GET {{host}}/

### Get recipes
# @name allRecipes
GET {{host}}/api/recipes

@firstId = {{allRecipes.response.body.$[0]._id}}

### Get one recipe
GET {{host}}/api/recipes/{{firstId}}

### Log in
#! Validation errors
GET {{host}}/auth/login
Content-Type: application/json

{
    "email": "bad@example",
    "password": "123456"
}

### Log in
#* Good credentials
GET {{host}}/auth/login
Content-Type: application/json

{
    "email": "good@example.org",
    "password": "awesomeSauce123!"
}

### Log out
GET {{host}}/auth/logout

### Add default recipe
#! 401 Unauthorized
# @name recipe
POST {{host}}/api/recipes
Content-Type: application/json

{
    "@type": "Recipe",
    "name": "Party Coffee Cake",
    "image": [
        {
            "@type": "ImageObject",
            "url": "https://example.com/photos/1x1/photo.jpg",
            "description": "Best thing since sliced bread.",
            "width": "400",
            "height": "300",
            "accessibilitySummary": "A slice of coffee cake with a steaming cup of tea."
        }
    ],
    "datePublished": "2018-03-10T00:00:00-05:00",
    "description": "This coffee cake is awesome and perfect for parties.",
    "prepTime": "PT20M",
    "cookTime": "PT30M",
    "totalTime": "PT50M",
    "keywords": [
        "cake", "party", "coffee"
    ],
    "recipeYield": "10",
    "recipeCategory": "Dessert",
    "recipeCuisine": "American",
    "recipeIngredient": [
        "2 cups of flour",
        "3/4 cup white sugar",
        "2 teaspoons baking powder",
        "1/2 teaspoon salt",
        "1/2 cup butter",
        "2 eggs",
        "3/4 cup milk"
    ],
    "recipeInstructions": [
        {
            "@type": "HowToStep",
            "name": "Preheat",
            "text": "Preheat the oven to 350 degrees F. Grease and flour a 9x9 inch pan.",
            "url": "https://example.com/party-coffee-cake#step1",
            "image": {
                "@type": "ImageObject",
                "url": "https://example.com/photos/party-coffee-cake/step1.jpg"
            }
        },
        {
            "@type": "HowToStep",
            "name": "Mix dry ingredients",
            "text": "In a large bowl, combine flour, sugar, baking powder, and salt.",
            "url": "https://example.com/party-coffee-cake#step2",
            "image": {
                "@type": "ImageObject",
                "url": "https://example.com/photos/party-coffee-cake/step2.jpg"
            }
        },
        {
            "@type": "HowToStep",
            "name": "Add wet ingredients",
            "text": "Mix in the butter, eggs, and milk.",
            "url": "https://example.com/party-coffee-cake#step3",
            "image": {
                "@type": "ImageObject",
                "url": "https://example.com/photos/party-coffee-cake/step3.jpg"
            }
        },
        {
            "@type": "HowToStep",
            "name": "Spread into pan",
            "text": "Spread into the prepared pan.",
            "url": "https://example.com/party-coffee-cake#step4",
            "image": {
                "@type": "ImageObject",
                "url": "https://example.com/photos/party-coffee-cake/step4.jpg"
            }
        },
        {
            "@type": "HowToStep",
            "name": "Bake",
            "text": "Bake for 30 to 35 minutes, or until firm.",
            "url": "https://example.com/party-coffee-cake#step5",
            "image": {
                "@type": "ImageObject",
                "url": "https://example.com/photos/party-coffee-cake/step5.jpg"
            }
        },
        {
            "@type": "HowToStep",
            "name": "Enjoy",
            "text": "Allow to cool and enjoy.",
            "url": "https://example.com/party-coffee-cake#step6",
            "image": {
                "@type": "ImageObject",
                "url": "https://example.com/photos/party-coffee-cake/step6.jpg"
            }
        }
    ],
    "video": {
        "@type": "VideoObject",
        "name": "How to make a Party Coffee Cake",
        "description": "This is how you make a Party Coffee Cake.",
        "url": "https://www.example.com/video123.mp4",
        "embedUrl": "https://www.example.com/videoplayer?video=123",
        "uploadDate": "2018-02-05T08:00:00+08:00",
        "duration": "PT1M33S",
        "expires": "2019-02-05T08:00:00+08:00"
    }
}

#### Variables
@recipeId = {{recipe.response.body._id}}

### Verify recipe was added
GEt {{host}}/api/recipes/{{recipeId}}

### Delete recipe
DELETE {{host}}/api/recipes/{{recipeId}}

### Add a recipe
# @name recipe
POST {{host}}/api/recipes
Content-Type: application/json

{
    "datePublished": "2020-02-06T20:29:39.000-05:00",
    "author": [
        {
            "@type": "Person",
            "name": "Samantha Hamilton",
            "url": "https://www.allrecipes.com/cook/7722043"
        }
    ],
    "description": "This chicken pot pie with potatoes uses a prepared double-crust pastry to help achieve this easy, beginner-friendly recipe your family will love.",
    "image": {
        "@type": "ImageObject",
        "url": "https://www.allrecipes.com/thmb/sv91ZuSJo57J9sBdqugJnnk5EW0=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/1100114-cbb1df92c384480aa26f3bc05f03974e.jpg",
        "height": 960,
        "width": 960
    },
    "name": "Mom&#39;s Chicken Pot Pie",
    "cookTime": "PT45M",
    "prepTime": "PT10M",
    "recipeCategory": [
        "Lunch",
        "Dinner"
    ],
    "recipeCuisine": [
        "U.S.",
        "American"
    ],
    "nutrition": {
        "@type": "NutritionInformation",
        "calories": "701 kcal",
        "carbohydrateContent": "66 g",
        "cholesterolContent": "55 mg",
        "fiberContent": "4 g",
        "proteinContent": "17 g",
        "saturatedFatContent": "16 g",
        "sodiumContent": "900 mg",
        "sugarContent": "7 g",
        "fatContent": "41 g",
        "unsaturatedFatContent": "0 g"
    },
    "recipeIngredient": [
        "0.33333334326744 cup butter",
        "0.33333334326744 cup chopped onion",
        "0.33333334326744 cup all-purpose flour",
        "0.5 teaspoon salt",
        "0.25 teaspoon ground black pepper",
        "1.75 cups chicken broth",
        "0.66666668653488 cup milk",
        "2 cups chopped cooked chicken",
        "1 (14.5 ounce) can peas and carrots",
        "0.5 (15 ounce) can whole new potatoes, drained",
        "1 (15 ounce) package prepared double-crust pie pastry"
    ],
    "recipeInstructions": [
        {
            "@type": "HowToStep",
            "text": "Preheat the oven to 425 degrees F (220 degrees C)."
        },
        {
            "@type": "HowToStep",
            "text": "Melt butter in a large skillet over medium heat. Cook and stir onion, flour, salt, and pepper in hot butter until onion is translucent, about 5 minutes."
        },
        {
            "@type": "HowToStep",
            "text": "Pour in broth and milk; bring to a boil and cook until slightly thickened, about 1 minute. Remove the skillet from heat and stir in chicken, peas and carrots, and potatoes."
        },
        {
            "@type": "HowToStep",
            "text": "Press 1 pie pastry into the bottom of a 9-inch, deep-dish pie pan. Pour chicken mixture into pie pastry. Top with remaining pastry and press edges together to seal. Cut several slits in top pastry. Place pie on a baking sheet."
        },
        {
            "@type": "HowToStep",
            "image": [
                {
                    "@type": "ImageObject",
                    "url": "https://www.allrecipes.com/thmb/sv91ZuSJo57J9sBdqugJnnk5EW0=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/1100114-cbb1df92c384480aa26f3bc05f03974e.jpg"
                }
            ],
            "text": "Bake in the preheated oven until crust is golden brown, about 30 minutes. Let pie cool and filling thicken at room temperature for 15 to 20 minutes before cutting."
        }
    ],
    "recipeYield": [
        "8"
    ],
    "totalTime": "PT70M"
}

#### Variables
@recipeId = {{recipe.response.body._id}}

### Update the record
PUT {{host}}/api/recipes/{{recipeId}}
Content-Type: application/json

{
    "name": "Grandma&#39;s Chicken Pot Pie",
    "keywords": [
        "family recipe"
    ]
}

### Verify updated
GET {{host}}/api/recipes/{{recipeId}}

### Delete this record
DELETE {{host}}/api/recipes/{{recipeId}}

### Add a recipe
#! Validation errors
POST {{host}}/api/recipes
Content-Type: application/json

{
    "name": "",
    "image": "should be an object",
    "cookTime": "15 minutes",
    "url": "not a valid url"
}

### Get some ingredients
GET {{host}}/api/ingredients

### Add ingredient
# @name ingredient
POST {{host}}/api/ingredients
Content-Type: application/json

{
    "name": "milk",
    "servingSize": "1 cup",
    "calories": "122 calories"
}

#### Variables
@ingredientId = {{ingredient.response.body._id}}

### Verify ingredient was added
GET {{host}}/api/ingredients/{{ingredientId}}

### Delete ingredient
DELETE {{host}}/api/ingredients/{{ingredientId}}

### Add ingredient
#! Validation errors
POST {{host}}/api/ingredients
Content-Type: application/json

{
    "name": "",
    "servingSize": "1 gal",
    "calories": "122"
}
